SELECT ANIMAL_INS.ANIMAL_ID AS ANIMAL_ID, ANIMAL_INS.NAME AS NAME
FROM ANIMAL_INS, ANIMAL_OUTS
WHERE ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
ORDER BY DATEDIFF(ANIMAL_OUTS.DATETIME, ANIMAL_INS.DATETIME) DESC
LIMIT 2

-- TIMEDIFF 사용해서 틀렸음